/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.robodsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRoboDslScopeProvider extends DelegatingScopeProvider {
}
