<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="roboEMF" nsURI="http://www.example.org/roboEMF" nsPrefix="roboEMF">
  <eClassifiers xsi:type="ecore:EClass" name="EScript">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainbody" lowerBound="1"
        eType="#//MainBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SubBody">
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" upperBound="-1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MainBody">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="commandmain" upperBound="-1"
        eType="#//CommandMain" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="command" upperBound="-1"
        eType="#//Command" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EString" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EInteger" instanceClassName="java.lang.Integer"/>
  <eClassifiers xsi:type="ecore:EClass" name="EComment" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comment" eType="#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="IfStatement" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subbody" lowerBound="1"
        eType="#//SubBody" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionmodel" lowerBound="1"
        eType="#//ConditionModel" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="elsebody" eType="#//SubBody"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WhileStatement" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subbody" lowerBound="1"
        eType="#//SubBody" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conditionmodel" lowerBound="1"
        eType="#//ConditionModel" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepeateStatement" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="#//EInteger"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="subbody" lowerBound="1"
        eType="#//SubBody" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Condition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoutineDecl" eSuperTypes="#//CommandMain">
    <eStructuralFeatures xsi:type="ecore:EReference" name="subbody" lowerBound="1"
        eType="#//SubBody" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RoutineCall" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="decl" lowerBound="1" eType="#//RoutineDecl"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TurnLeftCmd" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="TraceCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="trace" eType="#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DropCmd" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="StepCmd" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="PickCmd" eSuperTypes="#//Command"/>
  <eClassifiers xsi:type="ecore:EClass" name="DropMarkCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PickMarkCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DestroyWallCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BuildWallCmd" eSuperTypes="#//Command">
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//Location" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Full" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Mark" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="WallAhead" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="row" eType="#//EInteger"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="col" eType="#//EInteger"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BracketsCond">
    <eStructuralFeatures xsi:type="ecore:EReference" name="orcond" eType="#//OrCond"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="#//Condition"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NotCond">
    <eStructuralFeatures xsi:type="ecore:EReference" name="brackets" eType="#//BracketsCond"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="not" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AndCond">
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//NotCond"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//AndCond"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OrCond" eSuperTypes="#//ConditionModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="rhs" eType="#//OrCond"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="lhs" eType="#//AndCond"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommandMain"/>
  <eClassifiers xsi:type="ecore:EClass" name="Heading" eSuperTypes="#//Condition"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConditionModel"/>
</ecore:EPackage>
