/*
 * generated by Xtext 2.11.0
 */
package org.xtext.example.robodsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.example.mydsl.ui.internal.MydslActivator;

public class RoboDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("org.xtext.example.robodsl.RoboDsl");
	}

}
